version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing npm...
      - npm install -g yarn
      - node -v
      - npm -v
      - yarn -v
pre_build:
  commands:
    - echo Installing dependencies...
    - cd todo_app
    - yarn install
build:
  commands:
    - echo Building...
    - yarn build
artifacts:
  files:
    - "**/*"
  base-directory: todo_app/build